# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd0166e9a5e305e05aaaf15a45933cad3d1aaae926f733ce3b08ec299eae566207f340c2861a6e61d817bb727358238d2a2ffc1987b188bbe95e3ee24b2060e

test:
  secret_key_base: f00340af5ae2c8f401d3d574acc9ec59d07d89ccb6b88671e9e3a0669402e4129a8bf81e011d845a985d3e1f8514721b08b4dbbcf72496a8a4cb38e2c3be0d45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
